/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 mi19A_Blue.glb -T -M -j
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mi19A_Blue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1-11-05815F_8002'].geometry} material={materials.WHITESMOKE} />
      <mesh geometry={nodes['2-11-145F_8002'].geometry} material={materials.YELLOW} />
      <mesh geometry={nodes.Circle002.geometry} material={materials.Flash} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['GLASS-X19-BATT-COVER002_1'].geometry} material={materials['Glass.002']} />
        <mesh geometry={nodes['GLASS-X19-BATT-COVER002_2'].geometry} material={materials['Glass.002']} />
      </group>
      <mesh geometry={nodes['QT-X19-2M-CAM-LENS003'].geometry} material={materials['transp Glass']} />
      <mesh geometry={nodes['QT-X19-BATT-COVER-PRINTING-INK002'].geometry} material={materials.Material} />
      <mesh geometry={nodes['QT-X19-MAIN-CAM-LENS003'].geometry} material={materials['transp Glass']} />
      <mesh geometry={nodes['QT-X19-MAIN-MIC-MESH002'].geometry} material={materials.GRAY34} />
      <mesh geometry={nodes['QT-X19-SPK-MESH002'].geometry} material={materials.mesh} />
      <mesh geometry={nodes['QT-X19-SUB-CAM-LENS003'].geometry} material={materials['transp Glass']} />
      <mesh geometry={nodes['SJ-X19-BOT-COVER002'].geometry} material={materials.PHONE_COLOR_1} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2009'].geometry} material={materials.Camera_Black} />
      <mesh geometry={nodes.SOLID039.geometry} material={materials.Black_Gummi} />
      <mesh geometry={nodes.redmi.geometry} material={materials.labels} position={[0.022, -0.059, -0.003]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.163} />
      <mesh geometry={nodes.Circle.geometry} material={materials.labels} position={[0.007, 0.045, -0.003]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} />
      <mesh geometry={nodes['02_GLASS_X19_TP002_1'].geometry} material={materials.Screen_Black} />
      <mesh geometry={nodes['02_GLASS_X19_TP002_2'].geometry} material={materials.Screen_1} />
      <mesh geometry={nodes['02_GLASS_X19_TP002_3'].geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Lens_1006_1.geometry} material={materials.Lens} />
      <mesh geometry={nodes.Lens_1006_2.geometry} material={materials.Camera_Black_Metallic} />
      <mesh geometry={nodes.Lens_1008_1.geometry} material={materials.Lens} />
      <mesh geometry={nodes.Lens_1008_2.geometry} material={materials.Camera_Black_Metallic} />
      <mesh geometry={nodes.Lens_1009_1.geometry} material={materials.Lens} />
      <mesh geometry={nodes.Lens_1009_2.geometry} material={materials.Camera_Black_Metallic} />
      <mesh geometry={nodes.Lens_1010_1.geometry} material={materials.Lens} />
      <mesh geometry={nodes.Lens_1010_2.geometry} material={materials.Camera_Black_Metallic} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2007_1'].geometry} material={materials.Black_Glossy} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2007_2'].geometry} material={materials.Camera_Black} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2007_3'].geometry} material={materials.Camera_Black_Glossy} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2008_1'].geometry} material={materials.Black_Glossy} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2008_2'].geometry} material={materials.Camera_Black} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-2008_3'].geometry} material={materials.Camera_Black_Glossy} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-3002_1'].geometry} material={materials.Black_Glossy} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-3002_2'].geometry} material={materials.Camera_Black} />
      <mesh geometry={nodes['SJ-X19-DECO-RING-3002_3'].geometry} material={materials.Camera_Black_Glossy} />
      <mesh geometry={nodes['SJ-X19A-CAM-DECO-50M002_1'].geometry} material={materials.Chrome} />
      <mesh geometry={nodes['SJ-X19A-CAM-DECO-50M002_2'].geometry} material={materials.Camera_Black_Glossy} />
      <mesh geometry={nodes.TYPE_C_GEEK_615_304_010002_1.geometry} material={materials.bc} />
      <mesh geometry={nodes.TYPE_C_GEEK_615_304_010002_2.geometry} material={materials.GRAY25} />
      <mesh geometry={nodes.TYPE_C_GEEK_615_304_010002_3.geometry} material={materials.IVORY} />
    </group>
  )
}

useGLTF.preload('/mi19A_Blue-transformed.glb')
