/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 BLACK.glb --transform
*/

import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function MobileBlack(props) {
  const { nodes, materials } = useGLTF('/BLACK-transformed.glb')
  const groupRef = useRef();
  //to rotate the model
   useFrame(() => {
     groupRef.current.rotation.y += 0.01; 
   })

  return (
    <group ref={groupRef} scale={24} position={[0,-1.5,0]} {...props} dispose={null}>
      <group position={[-0.002, 0.124, -0.002]} rotation={[3.086, 0.009, 0.022]} scale={[1, 1, 1.006]}>
        <mesh geometry={nodes['02-FLASH-LENS_M16U001_1'].geometry} material={materials['Level 25.001']} />
        <mesh geometry={nodes['02-FLASH-LENS_M16U001_2'].geometry} material={materials.FLASH} />
      </group>
      <mesh geometry={nodes['02_CAM_DECO_LENS6_GLASS_M2_1'].geometry} material={materials['CAM GLASS']} position={[0.006, 0.135, -0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['02_CAM_DECO_SCREW_LV_OUT_M2_body1'].geometry} material={materials['PHONE BACK BLACK M16U']} position={[0.008, 0.135, -0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['02_METAL_MID_HSG_0902_M2_1_1_1'].geometry} material={materials['PHONE SIDE BLACK M16U']} position={[-0.004, 0.161, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['03_80018A1_01_NEW_MAX'].geometry} material={materials.lens} position={[0.016, 0.127, 0.001]} rotation={[-0.508, 1.569, -0.47]} scale={1.012} />
      <mesh geometry={nodes['03_80018A1_01_NEW_MAX001'].geometry} material={materials['Material.009']} position={[0.016, 0.127, 0.001]} rotation={[-0.508, 1.569, -0.47]} scale={1.012} />
      <group position={[0.006, 0.137, -0.004]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh2118.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Mesh2118_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes['04_LOGO_PU_GF_TOP_M2_body1'].geometry} material={materials.LOG} position={[0.019, 0.028, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['50406A1_REVIEW_H_1_1'].geometry} material={materials['Material.003']} position={[-0.004, 0.156, 0.006]} rotation={[-0.368, -1.57, -1.829]} />
      <mesh geometry={nodes.Curve.geometry} material={materials['Material.013']} position={[-0.003, 0.127, -0.004]} rotation={[1.571, 0, Math.PI]} />
      <mesh geometry={nodes.M2_AMB673ZX02_CG_35_body1.geometry} material={materials['SCREEN.001']} position={[-0.004, 0.091, 0.008]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.POL_11_1.geometry} material={materials['Material.001']} position={[-0.004, 0.117, 0.007]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.SENSOR_L_P_C_AMS_TCS3408_body1001.geometry} material={materials['Material.012']} position={[-0.003, 0.137, -0.003]} rotation={[0.368, -1.57, 1.668]} />
    </group>
  )
}

useGLTF.preload('/BLACK-transformed.glb')
